[honeypot]
172.17.1.51 ansible_user=sara ansible_ssh_pass=sara ansible_become_pass=sara

[suricata]
172.16.1.1 ansible_user=sara ansible_ssh_pass=sara ansible_become_pass=sara

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
