name: "DevSecOps Pipeline: AI-IDS & EVENG Automation"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Python-Security-Audit:
    name: "Python Quality & Security Audit"
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1: Checkout Code"
        uses: actions/checkout@v4
      - name: "Step 2: Set up Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Step 3: Install Security Tools"
        run: pip install flake8 bandit pip-audit
      - name: "Step 4: SAST (Bandit Scan)"
        # إضافة -s لتخطي تحذيرات الـ Webhook
        run: bandit -r . -ll -s B605,B104

  Ansible-Validation:
    name: "Ansible Syntax Check"
    needs: Python-Security-Audit
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1: Checkout Code"
        uses: actions/checkout@v4
      - name: "Step 2: Install Ansible"
        run: pip install ansible
      - name: "Step 3: Ansible Syntax Check"
        working-directory: ./ansible  # مهم جداً للدخول للفولدر الصح
        run: |
          ansible-playbook site.yml --syntax-check
          ansible-playbook block_attacker.yml --syntax-check
          ansible-playbook trap_attacker.yml --syntax-check

  Deploy-to-EvENg:
    name: "Deploy to EVENg"
    needs: Ansible-Validation
    runs-on: self-hosted
    steps:
      - name: "Step 1: Checkout Code"
        uses: actions/checkout@v4
      - name: "Step 2: Execute Ansible Playbook"
        working-directory: ./ansible # مهم جداً
        run: |
          ansible-playbook -i inventory.ini site.yml
